export { StatCard, TabBar, Footer, TopBar } from "@/src/shared/components";
export { StatusBadge } from "./StatusBadge";
export { QuickActions } from "./QuickActions";
export { PapersTable } from "./PapersTable";
export { PendingActionsList } from "./PendingActionsList";
export { ActivityFeed } from "./ActivityFeed";
export { DashboardHeader } from "./dashboard.header";
export { StatsSection } from "./stats.section";
export { PapersSection } from "./papers.section";
export { PapersTableClient } from "./papers-table.client";
export { PendingSection } from "./pending.section";
export { ActivitySection } from "./activity.section";
export { TabsShellClient } from "./tabs.shell.client";
